[[language]]
name = "python"
auto-format = true
formatter = { command = "/home/eman/.local/bin/ruff", args = ["-w"] }

[[language]]
name = "verilog"
auto-format = true
formatter = { command = "/opt/verible/bin/verible-verilog-format", args = ["-w"] }
comment-token = "//"
language-servers = ["verible-verilog-ls"]

[language-server.verible-verilog-ls]
command = "/opt/verible/bin/verible-verilog-ls"

[[language]]
name = "c"
auto-format = true
formatter = ["clang-format"]

[[language]]
name = "gleam"
auto-format = true
formatter = { command = "gleam", args = ["format", "--stdin"] }

[[grammar]]
name = "c"
source = { git = "https://github.com/tree-sitter/tree-sitter-c", rev = "f05e279aedde06a25801c3f2b2cc8ac17fac52ae" }

[[language]]
name = "cpp"
auto-format = true
formatter = ["clang-format"]

[[grammar]]
name = "cpp"
source = { git = "https://github.com/tree-sitter/tree-sitter-cpp", rev = "e8dcc9d2b404c542fd236ea5f7208f90be8a6e89" }

[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
formatter = ["gofmt"]
comment-token = "//"

[[language]]
name = "rust"
auto-format = true
formatter = ["rustfmt"]

[[language]]
name = "java"
auto-format = true
formatter = { command = "/opt/bin/google-java-format_linux-x86-64", args = ["-w"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "javascript"] }
